---
- name: install recent2
  hosts: all
  become: yes

  tasks:
  - name: make sure python3 and pip3 is installed
    package: 
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - python3-pip
  - name: install recent2 pip3 module
    shell: pip3 install recent2
